#!/bin/sh
#
# Abort commit if staged diff contains certain strings.
# Helps to avoid commiting debugging code or other temporary changes.
#
# An hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Forbidden strings space separated:
nocommittstrs="pdb DONOTCOMMIT"


red='\e[0;31m'
NC='\e[0m'     # No Color
for nocommit in $nocommittstrs; do
    if [ -n "$(git diff --cached|grep '+.*'${nocommit})" ]
    then 
        echo -e "${red}Error: Attempt to commit code containing '${nocommit}'.${NC}"
        echo
        git diff --cached|grep --color -B 5 -A 2 "+.*${nocommit}.*$"
        exit 1
    fi
done
